Canasta 1.1.1
CanastaWiki/Canasta pull request #112
Opened 2022-06-20 22:49 UTC by jeffw16

Slated for release on 2022-07-01.

Includes bug fixes and removal of extensions that are deprecated by Canasta.

Pull requests that will be included in this release:

- #99 (merged)
- #105

2022-07-11 15:41 UTC, jeffw16 commented
NOTE: Please don't merge until #117 is merged into this PR

2022-07-13 10:44 UTC, vedmaka requested changes
the build is erroring with `Unable to find a version "2.4.53-1~deb11u1" for the package "apache2"`, it looks like the new stable version is `2.4.54-1~deb11u1`, I have created #124 for this and rest of packages need to be upgraded

2022-07-19 05:32 UTC, jeffw16 commented on _sources/canasta/CanastaDefaultSettings.php
> +$wgServer = getenv( 'MW_SITE_SERVER' ) ?? 'https://localhost';
Ah ok, I agree with making the `.env.example` have HTTPS by default but keeping this as just `http`..

2022-07-20 18:06 UTC, pastakhov approved these changes

2022-07-20 20:58 UTC, merged