Fully install EmailAuthorization extension
CanastaWiki/Canasta pull request #161
Opened 2022-11-27 19:19 UTC by yaronkoren

Fixes #155 .

2022-11-28 04:13 UTC, jeffw16 requested changes

2022-11-28 04:13 UTC, jeffw16 commented on Dockerfile
> +    && cd ../EmailAuthorization \
I think this should be `cd ../../EmailAuthorization`

2022-11-28 04:20 UTC, yaronkoren commented on Dockerfile
> +    && cd ../EmailAuthorization \
That might explain the error message, but are you sure about this? Does calling "git submodule update" bring one to a subdirectory?

2022-11-29 07:09 UTC, jeffw16 commented on Dockerfile
> +    && cd ../EmailAuthorization \
Calling `git submodule update` should not change the working directory.

2022-11-29 17:54 UTC, yaronkoren commented on Dockerfile
> +    && cd ../EmailAuthorization \
Okay. In that case, this current code is fine, no?

2022-12-06 16:54 UTC, yaronkoren commented on Dockerfile
> +    && cd ../EmailAuthorization \
The code has changed, so this has become irrelevant anyway.

2022-12-06 16:56 UTC, yaronkoren commented
Okay, after five attempts, I think I finally got these two extra lines to work. :) @jeffw16 - thoughts?

2022-12-09 18:12 UTC, vedmaka commented on Dockerfile
> +
While it's definitely good to have logically separated parts grouped into own `RUN` commands we have to take into account Docker schrodinger limit [1] [2] on maximum number of layers Dockerfile can contain (each `RUN` creates a new layer). So we better to be careful with that :)

1. https://github.com/docker/docs/issues/8230#issuecomment-475278273
2. https://stackoverflow.com/questions/39382518/whats-the-reason-for-the-42-layer-limit-in-docker/54936566#54936566

2022-12-09 18:32 UTC, yaronkoren commented on Dockerfile
> +
Oh, I didn't know about that. Well, I think the Dockerfile currently contains 23 "RUN" calls - and this patch would make it 24. But some of those RUN calls are for patches, and I think the MW 1.39 of Canasta (coming soon!) will have 6 fewer patches than there currently are. So once that is done, we will be down to 18. That seems fine, no?

2022-12-10 08:05 UTC, jeffw16 approved these changes
LGTM

2022-12-13 17:08 UTC, merged