Add header warning to some special pages if $wgSMTP not set
CanastaWiki/Canasta pull request #194
Opened 2022-12-22 20:35 UTC by yaronkoren

Fixes #145.

A new version of the now-abandoned #187.

2022-12-23 01:46 UTC, tosfos commented
Shouldn't it check if $wgEnableEmail is true?

2022-12-23 01:53 UTC, yaronkoren commented
How interesting - I didn't know about that setting. I looked it up, and also saw this, which is specifically for Special:Emailuser:

https://www.mediawiki.org/wiki/Manual:$wgEnableUserEmail

So probably the code should be checking both.

2022-12-27 08:22 UTC, pastakhov requested changes

2022-12-27 08:22 UTC, pastakhov commented on _sources/canasta/CanastaUtils.php
> +function showSMTPWarning( &$siteNotice, Skin $skin ) {{
I think there should be only one open brace {

and do we really need a name for the function there?  why can't we use anonymous function like:
```
$wgHooks['SiteNoticeAfter'][] = function ( &$siteNotice, Skin $skin ) {
...
};
```

2022-12-27 08:22 UTC, pastakhov commented on _sources/canasta/CanastaUtils.php
> +	$siteNotice .= '<div class="warningbox"><big>Please note that mailing does not currently work on this wiki, because Canasta requires <a href="https://www.mediawiki.org/wiki/Manual:$wgSMTP">$wgSMTP</
the  big tag is deprecated https://developer.mozilla.org/en-US/docs/web/html/element/big

2022-12-27 08:22 UTC, pastakhov commented on _sources/canasta/CanastaUtils.php
> +	if ( $wgEnableEmail == false || $wgSMTP !== false ) {
by default $wgSMTP is null (or at least can be null) and in this case it won't works as expected.   I would simplify this as:
```
if ( !$wgEnableEmail || $wgSMTP  ) {
    return true;
}
```

2022-12-27 16:32 UTC, yaronkoren commented
@pastakhov - thanks for these fix suggestions! I think I added all of them. The double curly bracket was just a copying error. $wgSMTP defaults to false, not null, but you're right that we might as well check for everything.

2022-12-28 07:01 UTC, jeffw16 commented
I will refrain from providing a review until @pastakhov has had a chance to confirm his comments have been fixed to his satisfaction.

2022-12-28 09:16 UTC, pastakhov approved these changes
I'm satisfied, at least it does not break wiki now.
just a few notices:
* since MediaWiki 1.22 (in 2015) no need to return true in hooks
* I don't see styles for "warningbox" class in 1.39, I would use Html::warningBox( 'my message' ) instead;

2022-12-28 15:00 UTC, yaronkoren commented
@pastakhov - thanks for the comments! I'm embarrassed that I never actually checked this code on an MW 1.39 wiki. The "warningbox" class indeed did not work. I've fixed the code, and tested it, so now it should work better.

2023-01-17 18:10 UTC, merged