add comments for CIDR ranges
CanastaWiki/Canasta pull request #210
Opened 2023-02-05 14:47 UTC by freephile

just wanted to test everything out to prep for something more useful

This commit adds only comments.

2023-02-20 01:59 UTC, jeffw16 commented
Wait, we can remove the `"` and PHP recognizes the CIDR ranges?

2023-02-27 04:30 UTC, jeffw16 requested changes
Please address my question about removing the quotes from the CIDR range.

2023-03-01 04:45 UTC, freephile commented
It was a typo.

Sorry!

I wonder about adding linting on commit to flag and reject bad commits early. This commit was made in the browser so not using the visual linting help of VSCode

2023-03-01 04:46 UTC, freephile commented
I'll amend the commit when I am back at my office

2023-03-29 04:27 UTC, freephile commented on _sources/canasta/CanastaDefaultSettings.php
The purpose of this commit is to 

1. order the CIDR blocks numerically
2. add comments that remind you what the block notation is equal to
3. make my first commit to learn the project tooling and workflow without complication :-)

This branch could be deleted, and I would take no offense.

2023-04-07 04:28 UTC, jeffw16 approved these changes

2023-04-07 06:20 UTC, merged