Move symlinks creation code from run-apache.sh to create-symlinks.sh
CanastaWiki/Canasta pull request #218
Opened 2023-03-03 14:34 UTC by yaronkoren

Partial fix for #217.

2023-03-15 18:46 UTC, jeffw16 requested changes

2023-03-15 19:01 UTC, yaronkoren commented on _sources/scripts/run-apache.sh
> +/create-symlinks.sh
I admit it looks weird, but that's how all the other .sh files are called - see here, for example:

https://github.com/CanastaWiki/Canasta/blob/master/_sources/scripts/run-apache.sh#L111

No idea about permissions - hopefully @olsonjaredm can chime in on that one, since he had to deal with that exact issue.

2023-04-07 04:28 UTC, jeffw16 approved these changes
LGTM

2023-04-07 06:23 UTC, merged

2023-05-12 02:29 UTC, freephile commented on _sources/scripts/run-apache.sh
> +/create-symlinks.sh
> Should this be ran with a relative path or with a more absolute path?

Notice [in the Dockerfile](https://github.com/CanastaWiki/Canasta/blob/d16138952fb687047d7d4f23a083508d558cc3dd/Dockerfile#LL648C1-L648C29) how scripts are copied from the **Docker context** into the container "working directory" of '/' `COPY _sources/scripts/*.sh /`

Note: this is very common. AND, the final path in the image is not "relative" to your git sources, it's relative to the container (image) filesystem created by Docker.

2023-05-12 02:30 UTC, freephile commented on _sources/scripts/run-apache.sh
> +/create-symlinks.sh
(I realize this is resolved, I just wanted to comment for clarity)