Preliminary Implementation of Wiki Farm Support for Canasta
CanastaWiki/Canasta pull request #250
Opened 2023-06-05 02:37 UTC by chl178

## Related Issue #57 

This pull request outlines my progress on the project as part of the Google Summer of Code ([GSoC](https://phabricator.wikimedia.org/T331346)) program. The objective of the project is to implement support for a wiki farm in Canasta, a Docker-based MediaWiki distribution.

## Background
Currently, Canasta offers a streamlined way to set up a feature-rich MediaWiki instance on virtually any server. However, it does not currently support running multiple wikis, or a wiki farm, within the same container. This project aims to fill this gap and provide the ability to run different wikis in the same container. The wikis could vary by directory (e.g., example.com/a, example.com/b), subdomain (e.g., a.example.com, b.example.com), or completely different domains (e.g., example1.com, example2.com).

In addition, this project intends to extend Canasta's command-line interface (CLI) to support wiki farm configuration. This would allow administrators to effortlessly create, manage, and delete individual wikis.

## Implementation Approach
To simplify management and facilitate use, I've implemented a shared common setting that applies to all wikis. Alongside this commonality, each wiki is distinguished by its unique ID and has its own customized settings. This allows for the definition of unique skins, extensions and configurations for each wiki. In this way, multiple wikis can run independently in a single container.

For wikis under directories, I have scripted an automatic generator generatewikihtaccess.sh for .htaccess files to manage access permissions.

## Test
As you can see three different wiki a, k and local run independently in one container.
![Screenshot from 2023-06-04 19-33-23](https://github.com/CanastaWiki/Canasta/assets/116774313/e2efcf06-3558-434a-a942-f697c7b2783f)
![Screenshot from 2023-06-04 19-34-56](https://github.com/CanastaWiki/Canasta/assets/116774313/8508a635-15dc-483c-a555-c418e379b0db)
![Screenshot from 2023-06-04 19-35-12](https://github.com/CanastaWiki/Canasta/assets/116774313/6198d60b-57ca-4274-927a-af9ab526919b)
They are under different domain names and different directories.

## Next Steps
While this initial implementation is a significant step towards our goal, there is still considerable work to do. The next phase of this project will focus on developing the Canasta CLI to make it even more user-friendly and efficient in managing wiki farms.
I'm looking forward to feedback and suggestions on how we can improve this implementation and successfully deliver the project's objectives.

2023-06-05 03:25 UTC, chl178 commented
## For people who want to test it locally
As this is an early version, it currently does not support CLI installation and can only be manually installed using docker-compose. You may refer to the official docker-compose manual installation [documentation](https://github.com/CanastaWiki/Canasta-Documentation/blob/main/setup.md#manual-installation) for guidance.

1. Modify your local hosts file to add an alias for 127.0.0.1 and restart the Apache service.
![Screenshot from 2023-06-04 19-54-27](https://github.com/CanastaWiki/Canasta/assets/116774313/f090a958-2c2a-4e93-92c7-8cd8994b5d18)
2. Download my canasta code and create an image by `docker build -t canastafarm . `
3. Replace the web image in the docker-compose.override.yml file with the image you've just built.
![Screenshot from 2023-06-04 19-59-09](https://github.com/CanastaWiki/Canasta/assets/116774313/ac05c273-c775-4a6a-a532-e274476d3fed)
4. Modify the caddyfile file in the docker-compose's config, add an alias in the form of http://{corresponding alias}.
![Screenshot from 2023-06-04 19-59-42](https://github.com/CanastaWiki/Canasta/assets/116774313/e6bd284c-a82e-4a33-938b-f5e4ca44ad2c) 
Note: Because this is local testing, if you use https, you might not be able to access it due to the web server lacking an SSL certificate. Therefore, you need to change https to http in order to disable Caddy's https.
5. Copy .env.example to .env, and modify MW_SITE_SERVER and MW_SITE_FQDN in the .env file, changing them both to start with http.
![Screenshot from 2023-06-04 20-02-23](https://github.com/CanastaWiki/Canasta/assets/116774313/515c67e0-3a10-4ee1-a339-e9ddef015c35)
6. Create a wikis.yaml file and place it in the config directory.
![Screenshot from 2023-06-04 20-03-20](https://github.com/CanastaWiki/Canasta/assets/116774313/bf5e9466-b6a0-4f9b-a40a-ee97eebc1d59)
7. Run the command `docker-compose up -d`
8. Navigate to the installation address and install MediaWiki.
9. After installation, restart the installation and choose a different database for another wiki (repeat as many times as the number of wikis you wanted to install).
![Screenshot from 2023-06-04 20-09-57](https://github.com/CanastaWiki/Canasta/assets/116774313/42f3d181-940d-464b-b64f-86ad053c08d8)
![Screenshot from 2023-06-04 20-12-37](https://github.com/CanastaWiki/Canasta/assets/116774313/525af97f-e633-4143-88b4-6315be46a355)
10. Run the command `docker-compose down`
11. Place the LocalSettings.php into the config, and add the commonsettings.php and each wiki's customized LocalSettings_wikiID.php.
![Screenshot from 2023-06-04 20-04-46](https://github.com/CanastaWiki/Canasta/assets/116774313/e11334c6-a9ca-4035-a885-f202d4030ab2)
![Screenshot from 2023-06-04 20-13-27](https://github.com/CanastaWiki/Canasta/assets/116774313/fdad3e14-1642-420e-8df3-79449bdfa366)
12. Run the command `docker-compose up -d` to complete the installation.

My docker-compose structure:
![Screenshot from 2023-06-04 20-21-38](https://github.com/CanastaWiki/Canasta/assets/116774313/94977321-4d8d-45bf-9612-520e2e06e54d)

2023-06-05 17:25 UTC, chl178 commented
@yaronkoren @jeffw16

2023-07-16 16:03 UTC, vedmaka commented
Some general comments:

- It looks like some changes to the job runner scripts are also necessary, to make it run against all the farm wikis ( `mwjobrunner.sh` , `mwsitemapgen.sh` , `mwtranscoder.sh` )
- The `update.php` run also need to be changed by adding support for multiple wikis
- Images directories ([$wgUploadDirectory](https://www.mediawiki.org/wiki/Manual:$wgUploadDirectory)) need to be also altered per wiki. Otherwise, files will be overwritten
- Not quite sure about Cansata preference here, but maybe it'd be nice to have the farm mode switch controlled not by `wikis.yaml` or `CommonSettings.php` file presence but by some ENV variable instead

Please do not treat my comments as a call to action but as suggestions

2023-07-17 19:09 UTC, jeffw16 requested changes

2023-07-17 19:09 UTC, jeffw16 commented on _sources/scripts/run-apache.sh
> +  update_htaccess
Will this method break when there is a single wiki on the system?

Keep in mind @vedmaka that we are changing things such that every Canasta instance will be a farm, and the default will be a single-wiki farm (i.e. a wiki farm with one wiki on it).

A "single-wiki farm" is not to be confused with a "single wiki farm". That's the importance of a hyphen!

2023-07-18 22:26 UTC, chl178 commented on _sources/canasta/FarmConfigLoader.php
> +$wgServer = "http://$serverName";
As @jeffw16 rightly noted, I used the hardcoded HTTP protocol for local testing purposes. I fully understand that this could pose a potential security threat in a production environment. This part of the code will be updated before the final release.

2023-07-18 22:45 UTC, chl178 commented
> Some general comments:
> 
> * It looks like some changes to the job runner scripts are also necessary, to make it run against all the farm wikis ( `mwjobrunner.sh` , `mwsitemapgen.sh` , `mwtranscoder.sh` )
> * The `update.php` run also need to be changed by adding support for multiple wikis
> * Images directories ([$wgUploadDirectory](https://www.mediawiki.org/wiki/Manual:$wgUploadDirectory)) need to be also altered per wiki. Otherwise, files will be overwritten
> * Not quite sure about Canasta preference here, but maybe it'd be nice to have the farm mode switch controlled not by `wikis.yaml` or `CommonSettings.php` file presence but by some ENV variable instead
> 
> Please do not treat my comments as a call to action but as suggestions

Thank @vedmaka  for your comments and feedback:
We've already initiated the process of resolving the issues concerning the upload and cache directories. This should ensure that files are not overwritten and each wiki in the farm has its own distinct space.

Regarding the ENV variables, we've had discussions with[ Daniel](dkinzler@wikimedia.org), a respected MediaWiki community developer. His advice was not to define too many environment variables. As the current practice in the MediaWiki community is to use a YAML file for setting up farms, we've decided to follow this established [practice](https://www.mediawiki.org/wiki/Manual:$wgWikiFarmSettingsDirectory).

We're taking into account your points on modifying the job runner scripts (mwjobrunner.sh, mwsitemapgen.sh, mwtranscoder.sh), and incorporating support for multiple wikis in update.php.

2023-07-19 03:25 UTC, jeffw16 requested changes

2023-07-19 03:25 UTC, jeffw16 commented on _sources/scripts/run-apache.sh
> +  for maintenance_script in $(find /maintenance-scripts/ -maxdepth 1 -mindepth 1 -type f -name "*.sh"); do
Could we make this order predictable (i.e. load lexicographically) rather than nondeterministic?

2023-07-19 03:25 UTC, jeffw16 commented on _sources/scripts/maintenance-scripts/mw_job_runner.sh
> +#!/bin/bash
Rename file to `1_mw_job_runner.sh`

2023-07-19 03:25 UTC, jeffw16 commented on _sources/scripts/maintenance-scripts/mw_transcoder.sh
> +#!/bin/bash
Rename file `2_mw_transcoder.sh`

2023-07-19 03:25 UTC, jeffw16 commented on _sources/scripts/maintenance-scripts/mw_sitemap_generator.sh
>  #!/bin/bash
Rename file `3_mw_sitemap_generator.sh`

2023-07-19 03:25 UTC, jeffw16 commented on _sources/canasta/FarmConfigLoader.php
> +$wgScriptPath = !empty( $path ) ? "/" . $path . "/w" : "/w";
In PHP, double quotes allow for string interpolation. There is no point in doing the current concatenation. You could replace it with `"/$path/w"`.

2023-07-19 03:25 UTC, jeffw16 commented on _sources/canasta/FarmConfigLoader.php
> +if ( $original_url=== false ) {
Nit: please put a space before the `===`

2023-07-19 03:25 UTC, jeffw16 commented on _sources/canasta/FarmConfigLoader.php
> +    $path = explode( '/', ltrim( $original_url, '/' ) )[0];
This assumes `explode()` will always return an array with at least one element.

Unfortunately, built-in PHP functions often return weird, quirky results. Please consider taking a closer look at the documentation available on PHP.net for each of these functions.

This line needs to be split into multiple lines, with proper error handling for the returned value from the `explode()` function.

2023-07-19 03:25 UTC, jeffw16 commented on _sources/canasta/FarmConfigLoader.php
> +$key = rtrim( $serverName . '/' . $path, '/' );
For the first argument of `rtrim`, you could use PHP string interpolation like so: `"$serverName/$path"`

Also, what if `$path` is empty?

2023-07-19 03:25 UTC, jeffw16 commented on _sources/canasta/FarmConfigLoader.php
> +if ( is_null( $wikiID ) && array_key_exists( $key, $urlToWikiIdMap ) ) {
What if `MW_WIKI_NAME` is `""`? How do you want to handle that edge case? (Genuinely curious on what your thoughts are here.)

2023-07-19 03:25 UTC, jeffw16 commented on _sources/canasta/FarmConfigLoader.php
> +    error_log( "Warning: $key does not exist in urlToWikiIdMap." );
Why is this only a warning and doesn't warrant a fatal error?

2023-07-19 03:25 UTC, jeffw16 commented on _sources/canasta/FarmConfigLoader.php
> +    require_once $firstFile;
Surround the file variable with parentheses.

i.e.: `require_once( $firstFile );`

2023-07-19 03:25 UTC, jeffw16 commented on _sources/canasta/FarmConfigLoader.php
> +    $firstFile = $files[0]; // get the first file, since glob() returns files sorted lexicographically
Why are we only getting the first file? We want to include all PHP files in this directory, while also loading `CommonSettings.php` first, then `LocalSettings.php`, then everything else from the glob. This way, people can segment their LocalSettings.php files with each file containing a discrete configuration that can be enabled/disabled by the PHP file's presence.

2023-07-19 03:25 UTC, jeffw16 commented on _sources/scripts/maintenance-scripts/mw_job_runner.sh
> +RJ=$MW_HOME/maintenance/runJobs.php
Please don't abbreviate this variable. It was confusing to me what it referred to until I found its definition. Please rename it to `RUN_JOBS_SCRIPT_PATH`.

It might be more verbose, but it's more descriptive. Verbose but descriptive variable names are typically more helpful than concise but nondescriptive variable names.

2023-07-19 03:25 UTC, jeffw16 commented on _sources/scripts/maintenance-scripts/mw_transcoder.sh
> +RJ=$MW_HOME/maintenance/runJobs.php
Please see my comments on the other file about the naming of this variable.

2023-07-19 03:25 UTC, jeffw16 commented on _sources/canasta/FarmConfigLoader.php
> +if ( isset( $_SERVER['SERVER_NAME'] ) ) {
What do we do if `$_SERVER['SERVER_NAME']` is empty?

2023-07-19 03:25 UTC, jeffw16 commented on _sources/canasta/FarmConfigLoader.php
> +    $serverName = $_SERVER['SERVER_NAME'];
Why are we calling `$_SERVER['SERVER_NAME']` again when we just invoked it in the condition of this `if` statement? Could we please refactor this out to be declared before the `if` statement?

2023-07-19 03:25 UTC, jeffw16 commented on _sources/canasta/FarmConfigLoader.php
> +    die('Unknown wiki.');
Nit: spacing

2023-07-21 05:03 UTC, jeffw16 requested changes
There's simple code style issues that should be fixable with a linter. Let me know when you've fixed them all and then I can continue my code review.

2023-07-21 05:03 UTC, jeffw16 commented on _sources/canasta/CanastaDefaultSettings.php
> +if ( file_exists( $canastaCommonSettingsFilePath ) ){
Space is needed between `)` and `{`.

I recommend you install a linter and a style-checker that will enforce the MediaWiki style guide as per https://www.mediawiki.org/wiki/Manual:Coding_conventions/PHP

2023-07-21 05:03 UTC, jeffw16 commented on _sources/canasta/CanastaDefaultSettings.php
> +if ( file_exists( $canastaLocalSettingsFilePath ) ){
Same here

2023-07-21 05:03 UTC, jeffw16 commented on _sources/canasta/FarmConfigLoader.php
> +    if ( count( $pathParts ) > 0 ){
Again, need space between `)` and `{`

2023-07-21 05:03 UTC, jeffw16 commented on _sources/canasta/FarmConfigLoader.php
> +    if ( $firstDirectory != "wiki" && $firstDirectory != "w") {
Need space between `"w"` and `)`

2023-07-21 11:21 UTC, vedmaka commented on _sources/scripts/run-apache.sh
> +  update_htaccess
Oh, I did not know that in that case, this makes sense

2023-08-09 03:41 UTC, yaronkoren commented on _sources/scripts/maintenance-scripts/mw_job_runner.sh
> +#!/bin/bash
Sorry, I only saw this now. I disagree with this - whether or not these three maintenance scripts should get renamed, the renaming should not happen in this patch.

2023-09-12 17:01 UTC, closed without merging