Remove the CanastaUtils.php file (remove error message about $wgSMTP)
CanastaWiki/Canasta pull request #349
Opened 2024-01-08 20:20 UTC by pastakhov

2024-01-08 20:24 UTC, yaronkoren commented
@pastakhov - can you explain this change? Isn't it useful for people to know that emails will not be sent?

2024-01-08 20:37 UTC, pastakhov commented
This is for the `wikiteq` branch, and the docker image can send emails well if Postfix on the host is configured to accept emails from the docker network. We usually configure postfix on all servers, and the message is confusing for us

2024-01-08 20:50 UTC, yaronkoren commented
Oh, I didn't realize this was for the wikiteq branch. Thanks for the explanation.

Better yet, I would think, would be some flag to tell Canasta that mailing does work (outside of $wgSMTP). Or maybe Postfix can just be added to Canasta? I didn't realize this was a possibility.

2024-01-08 21:19 UTC, pastakhov commented
It is easier to have one configured Postfix on the host which worries about sending email messages. All Canasta and any other service on the server needs is to send the emails to Postfix on the host. This is the best practice.

2024-01-08 22:11 UTC, yaronkoren commented
Thanks for letting me know - I will definitely look into this Postfix thing.

Feel free to do whatever you want with this patch, though I still think the best option is to keep this code, but add another configuration variable for the PHP code to check, or some other way for the code to know that emailing is enabled.

2024-01-10 15:36 UTC, vedmaka requested changes

2024-01-10 17:22 UTC, pastakhov commented on Dockerfile
> -COPY _sources/canasta/LocalSettings.php _sources/canasta/CanastaUtils.php _sources/canasta/CanastaDefaultSettings.php $MW_HOME/
Oh, thanks. I missed the CanastaDefaultSettings.php file

2024-01-10 17:29 UTC, pastakhov commented on Dockerfile
> -COPY _sources/canasta/LocalSettings.php _sources/canasta/CanastaUtils.php _sources/canasta/CanastaDefaultSettings.php $MW_HOME/
OMG, and I missed the LocalSettings.php and I didn't remove the CanastaUtils.php file...  looks like I need to drink a little less

2024-01-12 09:54 UTC, vedmaka approved these changes

2024-01-12 14:06 UTC, merged

2024-04-19 20:52 UTC, jeffw16 commented
By the way, I would highly recommend adding back the `CanastaUtils.php` file, even if it's empty. I understand that none of the contents were applicable to Taqasta, and I agree with removing those lines of code. However, removing files will make the Canasta–Taqasta divide even greater.

2024-04-19 20:53 UTC, jeffw16 commented
We always reserve the right to add stuff to CanastaUtils.php, so I don't think we should be removing the file.