Feature/sitemap ping
CanastaWiki/Canasta pull request #36
Opened 2022-02-26 13:40 UTC by vedmaka

2022-02-27 11:05 UTC, pastakhov requested changes

2022-02-27 11:05 UTC, pastakhov commented on _sources/scripts/mwsitemapgen.sh
> +    echo "sending to Google -> https://www.google.com/ping?sitemap=$MW_SITE_SERVER/$MW_SCRIPT_PATH/sitemap/$MW_SITEMAP_SUBDIR/sitemap-index-$MW_SITEMAP_IDENTIFIER.xml"
I think we don't need / before $WG_SCRIPT_PATH because it already starts with /. (slash is doubled now)
slash is doubled also when MW_SITEMAP_SUBDIR is empty.
Also $WG_SITE_SERVER can be a protocol-relative url like `//site.name`

2022-03-03 18:51 UTC, pastakhov requested changes

2022-03-03 18:51 UTC, pastakhov commented on _sources/scripts/run-apache.sh
> +        MW_SCRIPT_PATH=$MW_SCRIPT_PATH nice -n 20 runuser -c /mwsitemapgen.sh -s /bin/bash "$WWW_USER"
It looks like it was added by mistake, is not?

2022-03-09 23:41 UTC, vedmaka commented on _sources/scripts/run-apache.sh
> +        MW_SCRIPT_PATH=$MW_SCRIPT_PATH nice -n 20 runuser -c /mwsitemapgen.sh -s /bin/bash "$WWW_USER"
nope, actually the line 152 not removed is a mistake ;)

2022-03-15 03:07 UTC, amalpaul54111 commented
Does this issue #28 still exist in your current version?

2022-03-21 18:37 UTC, pastakhov commented on _sources/scripts/run-apache.sh
> +        MW_SCRIPT_PATH=$MW_SCRIPT_PATH nice -n 20 runuser -c /mwsitemapgen.sh -s /bin/bash "$WWW_USER"
ok then

2022-03-21 18:39 UTC, pastakhov approved these changes

2022-03-23 12:06 UTC, merged