Update base image to be Debian 11 Bullseye
CanastaWiki/Canasta pull request #39
Opened 2022-03-02 15:55 UTC by shreyaansjain06

Fixes issue #11

2022-03-02 17:04 UTC, shreyaansjain06 commented
So I need to update debian such that all tests should pass right?
Have I understood it properly if not please tell what I am missing?

2022-03-02 17:06 UTC, jeffw16 commented
Yes, if you take a look at the detailed error message of this last CI build, it runs into an error on the line that does an apt install. This needs to be diagnosed and fixed.

The image needs to:


1. build properly
2. run without bugs

2022-03-04 07:17 UTC, shreyaansjain06 commented
I tried running the tests locally and they are failing without even modifying the code i.e. with detain:10
<img width="841" alt="Screenshot 2022-03-04 at 12 43 11 PM" src="https://user-images.githubusercontent.com/86606251/156716935-87377105-75ca-466c-9986-965a6d4e268d.png">

Should I try to resolve the errors there so that test works fine and then work on the updating Debian base image or I am doing any mistake in running the tests locally?

2022-03-05 06:41 UTC, shreyaansjain06 commented
Please ignore previous comment I found solution of that error

2022-03-05 10:10 UTC, shreyaansjain06 commented
I am not able to get why this test is failing during apt-install Can you help me by pointing to the specific thing due to which this error is occurring so that I can fix it

2022-03-05 10:18 UTC, jeffw16 commented
I am guessing your computer has ran out of memory. Two things point me to this hypothesis:

1. The exit code is 137. https://www.google.com/search?q=exit+code+137&oq=exit+code+137&aqs=chrome.0.0i512l10.4103j0j1&sourceid=chrome&ie=UTF-8
2. It says it was "killed".

2022-03-05 10:45 UTC, shreyaansjain06 commented
Thanks for your reply 
I have resolved Storage error by increasing storage 
but I am getting this error of Failure Login 
<img width="841" alt="Screenshot 2022-03-05 at 4 13 41 PM" src="https://user-images.githubusercontent.com/86606251/156879824-71bdbdac-aa68-4f54-8553-8905a8f8ed27.png">

2022-03-05 11:13 UTC, jeffw16 commented
Hi, please use Google for these sorts of questions. https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

2022-03-05 11:16 UTC, shreyaansjain06 commented
Sorry for that but I googled and I did not got the solution 
I will not repeat this mistake in future

2022-03-07 08:12 UTC, shreyaansjain06 commented
It is not able to find the git version in tests when I changed debian:10 to debian:bullseye
```
#7 9.006 Unable to find a version "1:2.20.1-2+deb10u3" for the package "git"
```
I think for debian 11 bullseye the version of git needs to be changed to ```1:2.30.2-1``` [here](https://github.com/WikiWorks/Canasta/blob/298c97312f694903e77e09e08d6b5418016fc8a8/Dockerfile#L23)

Am I going in right direction or there may be some other cause of failure of the test?

2022-03-07 11:27 UTC, jeffw16 commented
@shreyaansjain06 Yeah the version will definitely need to be changed. Notice how the current version used has `+deb10u3` appended afterwards. Bullseye won't recognize this because its packages would need to contain `deb11` in the version.

2022-03-07 14:21 UTC, shreyaansjain06 commented
There is  `python3-pygments` in debian bullseye instead of `python-pygment` should I replace it?

2022-03-07 17:58 UTC, shreyaansjain06 commented
Thanks for your reply Jefrey

2022-03-07 19:28 UTC, shreyaansjain06 commented
I googled about this and found that this error is due to permissions of github token 
Either write permission can be given by UI or by Yaml file I have updated the file Should I push if you agree?

Below are the links supporting my point 
[link1](https://github.com/docker/build-push-action/issues/463#issuecomment-924995909)
[link2](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow)

2022-03-07 20:52 UTC, jeffw16 commented
That's fine, one of the contributors to Canasta who has repo write access will have the ability to run the tests.

2022-03-28 21:48 UTC, jeffw16 requested changes

2022-03-29 03:57 UTC, shreyaansjain06 commented on Dockerfile
>      && echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php.list \
Thanks for the review 
Removed the Sury's apt repository

2022-03-29 10:14 UTC, jeffw16 requested changes

2022-03-29 10:14 UTC, jeffw16 commented on Dockerfile
>      && echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php.list \
I don't believe you did. Maybe you forgot to push your changes to GitHub?

2022-03-29 10:54 UTC, amalpaul54111 commented on Dockerfile
> +    apache2=2.4.53-1~deb11u \
I think here there is a typo, `2.4.53-1~deb11u1` is the correct version.

2022-03-29 12:57 UTC, shreyaansjain06 commented on Dockerfile
> +    apache2=2.4.53-1~deb11u \
Yes you are right that was a typo

2022-03-29 13:14 UTC, shreyaansjain06 commented
Some packages version were updated, which was causing problem so I fixed them

2022-03-29 15:03 UTC, jeffw16 approved these changes
LGTM

2022-03-29 15:05 UTC, merged