Use GitHub mirrors instead of Gerrit
CanastaWiki/Canasta pull request #44
Opened 2022-03-08 14:30 UTC by shreyaansjain06

Fixes #35

2022-03-10 05:13 UTC, shreyaansjain06 commented
@jeffw16  can you please help me in it?

2022-03-10 23:58 UTC, jeffw16 commented
I'm not sure what's going, but also please note that GitHub says there are merge conflicts that need to be resolved.

2022-03-11 06:31 UTC, shreyaansjain06 commented
I have resolved the merge conflict this was due to merging of some pull requests after this pr was made

2022-03-17 06:47 UTC, shreyaansjain06 commented
Can anyone suggest me what should I do for the tests to pass?
I think there may be space issue due to which the test fails

2022-03-18 19:35 UTC, amalpaul54111 commented on Dockerfile
> +	&& git fetch "https://github.com/wikimedia/mediawiki-extensions-BreadCrumbs2" refs/changes/03/701603/1 \
This is the line that causes the build error and this is because GitHub doesn't contain this https://gerrit.wikimedia.org/g/mediawiki/extensions/BreadCrumbs2/+/refs/changes/03/701603/1 change or something related to that. As this change is fixing a Bad Title error and if this error doesn't exist in the later versions, you could checkout to an appropriate commit.

2022-03-19 07:31 UTC, shreyaansjain06 commented
Thanks for the help Amal 

These changes are not there in GitHub but are in Gerrit, so should I keep this [line](https://github.com/WikiWorks/Canasta/blob/892e58e8835a877f354a616fdc127c6940cd300a/Dockerfile#L165) as it is or make this pr a draft untill these changes are not added to GitHub?

2022-03-19 07:32 UTC, shreyaansjain06 commented on Dockerfile
> +	&& git fetch "https://github.com/wikimedia/mediawiki-extensions-BreadCrumbs2" refs/changes/03/701603/1 \
Thanks for the help Amal

2022-04-01 21:50 UTC, jeffw16 requested changes

2022-04-01 21:50 UTC, jeffw16 commented on Dockerfile
> +	git clone --depth 1 -b $MW_CORE_VERSION https://github.com/wikimedia/mediawiki-core.git $MW_HOME \
Please change to `https://github.com/wikimedia/mediawiki.git`

2022-07-20 20:58 UTC, closed without merging